app/authentication/urls.py
from django.urls import path
from app.authentication.app_views import authentication


app_name = 'authentication'
urlpatterns = [
    path('signin', authentication.signin, name='signin'),
    path('signout', authentication.signout, name='signout')
]

app/dashboard/urls.py
# Django
from app.dashboard.app_views import dashboard
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

# Application
from app.dashboard.api import dashboard as api
from app.dashboard.app_views import dashboard


app_name = 'dashboard'
urlpatterns = [
    path('', dashboard.garden_monitoring, name='garden_monitoring'),
    path('garden-control', dashboard.garden_control, name='garden_control'),
    path('garden-config', dashboard.garden_configuration, name='garden_configuration'),
    path('account-config', dashboard.account_configuration, name='account_configuration'),
    path('password-config', dashboard.password_configuration, name='password_configuration'),
    path('start-mixin', dashboard.start_mixin, name='start_mixin'),
    
    path('api/', include(([
        path('v1/', include(([
            path('currentvalue/', api.CurrentSensorValue.as_view(), name="currentvalue"),
            path('sensorcontrol/', api.GetDataControl.as_view(), name="sensorcontrol"),
            path('setdatacontrol1/', api.SetDataControlStage1.as_view(), name="setdatacontrol1"),
            path('setdatacontrol2/', api.SetDataControlStage2.as_view(), name="setdatacontrol2"),
            path('setdatacontrol3/', api.SetDataControlStage3.as_view(), name="setdatacontrol3"),
            path('setdatacontrol4/', api.SetDataControlStage4.as_view(), name="setdatacontrol4"),
            path('publishaction/', api.PublishControlMessage.as_view(), name="publishaction"),
        ], 'v1'), namespace='v1')),
    ], 'api'), namespace='api')),
    
    path('ied-mubarak.exe', TemplateView.as_view(template_name='base/index.html'))
]

app/fusioncharts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from fusioncharts.views import catalogue

from fusioncharts import datahandler
from fusioncharts.samples import rendering_angular_gauge_using_dictionary_example, rendering_column2d_chart_using_dictionary_example
from fusioncharts.samples import rendering_map_using_dictionary_example, rendering_multiseries_column2d_chart_using_json_example
from fusioncharts.samples import rendering_multiseries_StackedColumn2dline_using_json_example, rendering_pie3d_using_json_example
from fusioncharts.samples import rendering_column_line_area_combi_using_json_example, rendering_map_using_json_example
from fusioncharts.samples import rendering_angular_gauge_using_json_example, client_side_chart_export
from fusioncharts.samples import fetching_json_data_from_url, fetching_xml_data_from_url, fetching_data_from_database
from fusioncharts.samples import drilldown_from_database_example, rendering_charts_by_common_theme
from fusioncharts.samples import export_chart_using_export_handler
from fusioncharts.samples import dynamic_chart_resize, dynamic_chart_type, chart_annotation, chart_update_onclick
from fusioncharts.samples import chart_tooltip, rendering_chart_with_different_language, chart_special_chart
from fusioncharts.samples import product_life_cycle_event, special_event, chart_message, interactive_event, number_format_module
from fusioncharts.samples import special_chart_type_api, chart_instance_level_api, chart_product_level_api
from fusioncharts.samples import updating_chart_properties, highlight_specific_data_points, update_data_runtime
from fusioncharts.samples import get_data_from_scatter_chart
from fusioncharts.samples import Line_Chart_With_Time_Axis, Plotting_Multiple_Series_On_Time_Axis
from fusioncharts.samples import Column_and_line_combination_on_time_axis, Plotting_Two_Variables
from fusioncharts.samples import Different_Plot_Type_Chart, ColumnChart_With_Time_Axis
from fusioncharts.samples import AreaChart_With_Time_Axis, Interactive_candlestick_chart
from fusioncharts.samples import Annotating_single_data_point, Single_Event_Overlay
from fusioncharts.samples import Date_range_event_overlay, Adding_Reference_Line


urlpatterns = [
    url(r'^$', catalogue),
    url(r'^admin/', admin.site.urls),
    url(r'^datahandler', datahandler.getdata),
    url(r'^rendering-angular-gauge-using-dictionary-example', rendering_angular_gauge_using_dictionary_example.chart, name='chart'),
    url(r'^rendering-angular-gauge-using-json-example', rendering_angular_gauge_using_json_example.chart, name='chart'),
    url(r'^rendering-column2d-chart-using-dictionary-example', rendering_column2d_chart_using_dictionary_example.chart, name='chart'),
    url(r'^rendering-map-using-dictionary-example', rendering_map_using_dictionary_example.chart, name='chart'),
    url(r'^rendering-map-using-json-example', rendering_map_using_json_example.chart, name='chart'),
    url(r'^rendering-multiseries-column2d-chart-using-json-example', rendering_multiseries_column2d_chart_using_json_example.chart, name='chart'),
    url(r'^rendering-multiseries-StackedColumn2dline-using-json-example', rendering_multiseries_StackedColumn2dline_using_json_example.chart, name='chart'),
    url(r'^rendering-pie3d-using-json-example', rendering_pie3d_using_json_example.chart, name='chart'),
    url(r'^rendering-column-line-area-combi-using-json-example', rendering_column_line_area_combi_using_json_example.chart, name='chart'),
    url(r'^client-side-chart-export', client_side_chart_export.chart, name='chart'),
    url(r'^fetching-json-data-from-url', fetching_json_data_from_url.chart, name='chart'),
    url(r'^fetching-xml-data-from-url', fetching_xml_data_from_url.chart, name='chart'),
    url(r'^fetching-data-from-database', fetching_data_from_database.chart, name='chart'),
    url(r'^drilldown-from-database-example', drilldown_from_database_example.chart, name='chart'),
    url(r'^rendering-charts-by-common-theme', rendering_charts_by_common_theme.chart, name='chart'),
    url(r'^export-chart-using-export-handler', export_chart_using_export_handler.chart, name='chart'),
    url(r'^dynamic-chart-resize', dynamic_chart_resize.chart, name='chart'),
    url(r'^dynamic-chart-type', dynamic_chart_type.chart, name='chart'),
    url(r'^chart-annotation', chart_annotation.chart, name='chart'),
    url(r'^chart-update-onclick', chart_update_onclick.chart, name='chart'),
    url(r'^rendering-chart-with-different-language', rendering_chart_with_different_language.chart, name='chart'),
    url(r'^chart-special-chart', chart_special_chart.chart, name='chart'),
    url(r'^chart-tooltip', chart_tooltip.chart, name='chart'),
    url(r'^product-life-cycle-event', product_life_cycle_event.chart, name='chart'),
    url(r'^special-event', special_event.chart, name='chart'),
    url(r'^chart-message', chart_message.chart, name='chart'),
    url(r'^interactive-event', interactive_event.chart, name='chart'),
    url(r'^number-format-module', number_format_module.chart, name='chart'),
    url(r'^special-chart-type-api', special_chart_type_api.chart, name='chart'),
    url(r'^chart-instance-level-api', chart_instance_level_api.chart, name='chart'),
    url(r'^chart-product-level-api', chart_product_level_api.chart, name='chart'),
    url(r'^updating-chart-properties', updating_chart_properties.chart, name='chart'),
    url(r'^highlight-specific-data-points', highlight_specific_data_points.chart, name='chart'),
    url(r'^update-data-runtime', update_data_runtime.chart, name='chart'),
    url(r'^get-data-from-scatter-chart', get_data_from_scatter_chart.chart, name='chart'),
    url(r'^Line-Chart-With-Time-Axis', Line_Chart_With_Time_Axis.chart, name='chart'),
    url(r'^Plotting-Multiple-Series-On-Time-Axis', Plotting_Multiple_Series_On_Time_Axis.chart, name='chart'),
    url(r'^Column-and-line-combination-on-time-axis', Column_and_line_combination_on_time_axis.chart, name='chart'),
    url(r'^Plotting-Two-Variables', Plotting_Two_Variables.chart, name='chart'),
    url(r'^Different-Plot-Type-Chart', Different_Plot_Type_Chart.chart, name='chart'),
    url(r'^ColumnChart-With-Time-Axis', ColumnChart_With_Time_Axis.chart, name='chart'),
    url(r'^AreaChart-With-Time-Axis', AreaChart_With_Time_Axis.chart, name='chart'),
    url(r'^Interactive-candlestick-chart', Interactive_candlestick_chart.chart, name='chart'),
    url(r'^Annotating-single-data-point', Annotating_single_data_point.chart, name='chart'),
    url(r'^Single-Event-Overlay', Single_Event_Overlay.chart, name='chart'),
    url(r'^Date-range-event-overlay', Date_range_event_overlay.chart, name='chart'),
    url(r'^Adding-Reference-Line', Adding_Reference_Line.chart, name='chart') 
]

yukina/urls.py
# Django
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.dashboard.urls', namespace='dashboard')),
    path('', include('app.authentication.urls', namespace='authentication')),
]

templates/include/__footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 text-center">
                2020 © Aldion Amirrul Endryanto
            </div>
        </div>
    </div>
</footer>

templates/include/__header.html
{% load static %}
<header id="topnav">
    <nav class="navbar-custom">
        <ul class="list-unstyled topbar-right-menu float-right mb-0">
            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle nav-user" data-toggle="dropdown" href="#" role="button"
                    aria-haspopup="false" aria-expanded="false">
                    <img src="{% static 'images/users/avatar-1.jpg' %}" alt="user" class="rounded-circle"> <span class="ml-1">
                    {{ request.user.first_name }} {{ request.user.last_name }}
                        <i class="mdi mdi-chevron-down"></i> </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated profile-dropdown ">
                    <a href="{% url 'authentication:signout' %}" class="dropdown-item notify-item">
                        <i class="dripicons-power"></i> <span>Logout</span>
                    </a>
                    <a href="/admin/" class="dropdown-item notify-item">
                        <i class="dripicons-user"></i> <span>Admin Dashboard</span>
                    </a>
                </div>
            </li>
        </ul>


        <ul class="list-unstyled menu-left mb-0">
            <li class="float-left">
                <a href="index.html" class="logo">
                    <span class="logo-lg">
                        <img src="{% static 'images/logo.png' %}" alt="" height="20">
                    </span>
                    <span class="logo-sm">
                        <img src="{% static 'images/logo_sm.png' %}" alt="" height="28">
                    </span>
                </a>
            </li>
        </ul>
    </nav>
</header>

templates/include/__main.html
{% load static %}
<html lang="en">
    <head>
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
        <title>Yukina - Hydroponic Dashboard</title>

        {% block meta %}
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <meta content="Dashboard IoT untuk Kebun Hidroponik." name="description" />
            <meta content="Aldion" name="author" />
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        {% endblock %}

        {% block css %}
            <!-- DataTables -->
            <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>
            <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>

            <!-- Icons css -->
            <link href="{% static 'libs/@mdi/font/css/materialdesignicons.min.css' %}" rel="stylesheet" type="text/css" />
            <link href="{% static 'libs/dripicons/webfont/webfont.css' %}" rel="stylesheet" type="text/css" />
            <link href="{% static 'libs/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css" />

            <!-- App css -->
            <!-- build:css -->
            <link href="{% static 'css/app.css' %}" rel="stylesheet" type="text/css" />
        {% endblock %}
    </head>

    <body>

        <!-- Begin page -->
        <div id="wrapper">

            {% include 'include/__header.html' %}
            {% include 'include/__navbar.html' %}

            <!-- Page Content Start -->
            <div class="content-page">
                <div class="content">
                    <div class="container-fluid">
                        {% block breadcrumb %} {% endblock %}

                        {% block content %} {% endblock %}
                    </div>
                </div>
            </div>
            <!-- End Page Content-->

            <!-- Footer -->
            {% include 'include/__footer.html' %}
            <!-- End Footer -->

        </div>
        <!-- End #wrapper -->
        {% block javascript %}
            <!-- jQuery  -->
            <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
            <script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
            <script src="{% static 'libs/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
            <script src="{% static 'libs/metismenu/metisMenu.min.js' %}"></script>

            
        {% endblock %}
        <!-- App js -->
        <script src="{% static 'js/jquery.core.js' %}"></script>
        <script src="{% static 'js/jquery.app.js' %}"></script>
    </body>
</html>

templates/include/__navbar.html
<div class="left-side-menu">
    <div class="slimscroll-menu">
        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <ul class="metismenu" id="side-menu">
                <li class="menu-title">Dashboard</li>
                 <li>
                    <a href="{% url 'dashboard:garden_monitoring' %}">
                        <i class="mdi mdi-leaf"></i> <span>Monitoring Kebun</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'dashboard:garden_control' %}">
                        <i class="mdi mdi-pot-mix"></i> <span> Kontrol Kebun </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'dashboard:garden_configuration' %}">
                        <i class="mdi mdi-pot"></i> <span> Pengaturan Kebun </span>
                    </a>
                </li>

                <li class="menu-title">Akun</li>
                <li>
                    <a href="{% url 'dashboard:account_configuration' %}">
                        <i class="mdi mdi-account-settings-variant "></i> <span> Pengaturan Akun </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'authentication:signout' %}">
                        <i class="mdi mdi-logout"></i> <span> Logout</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Sidebar -->
        <div class="clearfix"></div>
    </div>
    <!-- Sidebar -left -->
</div>