app/dashboard/urls.py
# Django
from app.dashboard.app_views import dashboard
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

# Application
from app.dashboard.api import dashboard as api
from app.dashboard.app_views import dashboard


app_name = 'dashboard'
urlpatterns = [
    path('', dashboard.garden_monitoring, name='garden_monitoring'),
    path('garden-control', dashboard.garden_control, name='garden_control'),
    path('garden-config', dashboard.garden_configuration, name='garden_configuration'),
    path('account-config', dashboard.account_configuration, name='account_configuration'),
    path('password-config', dashboard.password_configuration, name='password_configuration'),
    path('start-mixin', dashboard.start_mixin, name='start_mixin'),
    
    path('api/', include(([
        path('v1/', include(([
            path('currentvalue/', api.CurrentSensorValue.as_view(), name="currentvalue"),
            path('sensorcontrol/', api.GetDataControl.as_view(), name="sensorcontrol"),
            path('setdatacontrol1/', api.SetDataControlStage1.as_view(), name="setdatacontrol1"),
            path('setdatacontrol2/', api.SetDataControlStage2.as_view(), name="setdatacontrol2"),
            path('setdatacontrol3/', api.SetDataControlStage3.as_view(), name="setdatacontrol3"),
            path('setdatacontrol4/', api.SetDataControlStage4.as_view(), name="setdatacontrol4"),
            path('publishaction/', api.PublishControlMessage.as_view(), name="publishaction"),
        ], 'v1'), namespace='v1')),
    ], 'api'), namespace='api')),
    
    path('ied-mubarak.exe', TemplateView.as_view(template_name='base/index.html'))
]

app/fusioncharts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from fusioncharts.views import catalogue

from fusioncharts import datahandler
from fusioncharts.samples import rendering_angular_gauge_using_dictionary_example, rendering_column2d_chart_using_dictionary_example
from fusioncharts.samples import rendering_map_using_dictionary_example, rendering_multiseries_column2d_chart_using_json_example
from fusioncharts.samples import rendering_multiseries_StackedColumn2dline_using_json_example, rendering_pie3d_using_json_example
from fusioncharts.samples import rendering_column_line_area_combi_using_json_example, rendering_map_using_json_example
from fusioncharts.samples import rendering_angular_gauge_using_json_example, client_side_chart_export
from fusioncharts.samples import fetching_json_data_from_url, fetching_xml_data_from_url, fetching_data_from_database
from fusioncharts.samples import drilldown_from_database_example, rendering_charts_by_common_theme
from fusioncharts.samples import export_chart_using_export_handler
from fusioncharts.samples import dynamic_chart_resize, dynamic_chart_type, chart_annotation, chart_update_onclick
from fusioncharts.samples import chart_tooltip, rendering_chart_with_different_language, chart_special_chart
from fusioncharts.samples import product_life_cycle_event, special_event, chart_message, interactive_event, number_format_module
from fusioncharts.samples import special_chart_type_api, chart_instance_level_api, chart_product_level_api
from fusioncharts.samples import updating_chart_properties, highlight_specific_data_points, update_data_runtime
from fusioncharts.samples import get_data_from_scatter_chart
from fusioncharts.samples import Line_Chart_With_Time_Axis, Plotting_Multiple_Series_On_Time_Axis
from fusioncharts.samples import Column_and_line_combination_on_time_axis, Plotting_Two_Variables
from fusioncharts.samples import Different_Plot_Type_Chart, ColumnChart_With_Time_Axis
from fusioncharts.samples import AreaChart_With_Time_Axis, Interactive_candlestick_chart
from fusioncharts.samples import Annotating_single_data_point, Single_Event_Overlay
from fusioncharts.samples import Date_range_event_overlay, Adding_Reference_Line


urlpatterns = [
    url(r'^$', catalogue),
    url(r'^admin/', admin.site.urls),
    url(r'^datahandler', datahandler.getdata),
    url(r'^rendering-angular-gauge-using-dictionary-example', rendering_angular_gauge_using_dictionary_example.chart, name='chart'),
    url(r'^rendering-angular-gauge-using-json-example', rendering_angular_gauge_using_json_example.chart, name='chart'),
    url(r'^rendering-column2d-chart-using-dictionary-example', rendering_column2d_chart_using_dictionary_example.chart, name='chart'),
    url(r'^rendering-map-using-dictionary-example', rendering_map_using_dictionary_example.chart, name='chart'),
    url(r'^rendering-map-using-json-example', rendering_map_using_json_example.chart, name='chart'),
    url(r'^rendering-multiseries-column2d-chart-using-json-example', rendering_multiseries_column2d_chart_using_json_example.chart, name='chart'),
    url(r'^rendering-multiseries-StackedColumn2dline-using-json-example', rendering_multiseries_StackedColumn2dline_using_json_example.chart, name='chart'),
    url(r'^rendering-pie3d-using-json-example', rendering_pie3d_using_json_example.chart, name='chart'),
    url(r'^rendering-column-line-area-combi-using-json-example', rendering_column_line_area_combi_using_json_example.chart, name='chart'),
    url(r'^client-side-chart-export', client_side_chart_export.chart, name='chart'),
    url(r'^fetching-json-data-from-url', fetching_json_data_from_url.chart, name='chart'),
    url(r'^fetching-xml-data-from-url', fetching_xml_data_from_url.chart, name='chart'),
    url(r'^fetching-data-from-database', fetching_data_from_database.chart, name='chart'),
    url(r'^drilldown-from-database-example', drilldown_from_database_example.chart, name='chart'),
    url(r'^rendering-charts-by-common-theme', rendering_charts_by_common_theme.chart, name='chart'),
    url(r'^export-chart-using-export-handler', export_chart_using_export_handler.chart, name='chart'),
    url(r'^dynamic-chart-resize', dynamic_chart_resize.chart, name='chart'),
    url(r'^dynamic-chart-type', dynamic_chart_type.chart, name='chart'),
    url(r'^chart-annotation', chart_annotation.chart, name='chart'),
    url(r'^chart-update-onclick', chart_update_onclick.chart, name='chart'),
    url(r'^rendering-chart-with-different-language', rendering_chart_with_different_language.chart, name='chart'),
    url(r'^chart-special-chart', chart_special_chart.chart, name='chart'),
    url(r'^chart-tooltip', chart_tooltip.chart, name='chart'),
    url(r'^product-life-cycle-event', product_life_cycle_event.chart, name='chart'),
    url(r'^special-event', special_event.chart, name='chart'),
    url(r'^chart-message', chart_message.chart, name='chart'),
    url(r'^interactive-event', interactive_event.chart, name='chart'),
    url(r'^number-format-module', number_format_module.chart, name='chart'),
    url(r'^special-chart-type-api', special_chart_type_api.chart, name='chart'),
    url(r'^chart-instance-level-api', chart_instance_level_api.chart, name='chart'),
    url(r'^chart-product-level-api', chart_product_level_api.chart, name='chart'),
    url(r'^updating-chart-properties', updating_chart_properties.chart, name='chart'),
    url(r'^highlight-specific-data-points', highlight_specific_data_points.chart, name='chart'),
    url(r'^update-data-runtime', update_data_runtime.chart, name='chart'),
    url(r'^get-data-from-scatter-chart', get_data_from_scatter_chart.chart, name='chart'),
    url(r'^Line-Chart-With-Time-Axis', Line_Chart_With_Time_Axis.chart, name='chart'),
    url(r'^Plotting-Multiple-Series-On-Time-Axis', Plotting_Multiple_Series_On_Time_Axis.chart, name='chart'),
    url(r'^Column-and-line-combination-on-time-axis', Column_and_line_combination_on_time_axis.chart, name='chart'),
    url(r'^Plotting-Two-Variables', Plotting_Two_Variables.chart, name='chart'),
    url(r'^Different-Plot-Type-Chart', Different_Plot_Type_Chart.chart, name='chart'),
    url(r'^ColumnChart-With-Time-Axis', ColumnChart_With_Time_Axis.chart, name='chart'),
    url(r'^AreaChart-With-Time-Axis', AreaChart_With_Time_Axis.chart, name='chart'),
    url(r'^Interactive-candlestick-chart', Interactive_candlestick_chart.chart, name='chart'),
    url(r'^Annotating-single-data-point', Annotating_single_data_point.chart, name='chart'),
    url(r'^Single-Event-Overlay', Single_Event_Overlay.chart, name='chart'),
    url(r'^Date-range-event-overlay', Date_range_event_overlay.chart, name='chart'),
    url(r'^Adding-Reference-Line', Adding_Reference_Line.chart, name='chart') 
]

yukina/urls.py
# Django
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.dashboard.urls', namespace='dashboard')),
    path('', include('app.authentication.urls', namespace='authentication')),
]

templates/base/dashboard/account_configuration.html
{% extends 'include/__main.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <!-- Sweet Alert css -->
    <link href="{% static 'libs/sweetalert2/sweetalert2.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'libs/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- Sweet Alert Js  -->
    <script src="{% static 'libs/sweetalert2/sweetalert2.min.js' %}"></script>
    <script src="{% static 'js/jquery.sweet-alert.init.js' %}"></script>

{% endblock %}

{% block breadcrumb %}
    <div class="page-title-box">
        <ol class="breadcrumb float-right">
            <li class="breadcrumb-item"><a href="javascript:void(0);">Akun</a></li>
            <li class="breadcrumb-item active">Pengaturan Akun</li>
        </ol>
        <h4 class="page-title">Pengaturan Akun</h4>
    </div>
{% endblock  %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}

                <div class="alert alert-dismissible bg-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} text-white border-0 fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong></strong> {{ message }}
                </div>

                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        
        <div class="col-lg-6 ">
            <div class="card-box bx-shadow-lg">
                <h4 class="m-t-0 header-title">Pengaturan Akun Pengguna</h4>
                <p>Form untuk mengkustomisasi data pada akun</p>
                <hr>
                
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="userName">Username<span class="text-danger">*</span></label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label for="emailAddress">Alamat Email<span class="text-danger">*</span></label>
                        {{ form.email }}
                    </div>                    
                    <div class="form-group">
                        <label for="firstname">Nama Depan<span class="text-danger">*</span></label>
                        {{ form.first_name }}
                    </div>  
                    <div class="form-group">
                        <label for="lastname">Nama Belakang<span class="text-danger">*</span></label>
                        {{ form.last_name }}
                    </div>  
                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary waves-effect waves-light" type="submit">
                            Simpan Perubahan
                        </button>                        
                    </div>

                </form>
            </div> <!-- end card-box -->
        </div>


        <div class="col-xl-6">            
            <div class="card-box bx-shadow-lg">
                <h4 class="m-t-0 header-title">Konfigurasi Password Akun</h4>
                <p>Untuk mengubah password pada akun anda, silahkan klik tombol berikut</p>
                <hr>
                
                <a href="{% url 'dashboard:password_configuration' %}" style="color:white;" class="btn btn-success">
                    <i class="mdi mdi-lock"></i>
                    Ganti Password
                </a>
            </div> <!-- end card-box -->
        </div> <!-- end col -->

    <!-- end row -->
    </div>
{% endblock %}

templates/base/dashboard/garden_configuration.html
{% extends 'include/__main.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <!-- Sweet Alert css -->
    <link href="{% static 'libs/sweetalert2/sweetalert2.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'libs/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- Sweet Alert Js  -->
    <script src="{% static 'libs/sweetalert2/sweetalert2.min.js' %}"></script>
    <script src="{% static 'js/jquery.sweet-alert.init.js' %}"></script>

{% endblock %}

{% block breadcrumb %}
    <div class="page-title-box">
        <ol class="breadcrumb float-right">
            <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
            <li class="breadcrumb-item active">Pengaturan Kebun</li>
        </ol>
        <h4 class="page-title">Pengaturan Kebun</h4>
    </div>
{% endblock  %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}

                <div class="alert alert-dismissible bg-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} text-white border-0 fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong></strong> {{ message }}
                </div>

                {% endfor %}
            {% endif %}
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        
        <div class="col-lg-6 ">
            <div class="card-box bx-shadow-lg">
                <h4 class="m-t-0 header-title">Konfigurasi Nilai Ideal Kondisi Tanaman</h4>
                <p>Form untuk menyetel nilai ideal monitoring pada tanaman hidroponik</p>
                <hr>
                <form method="POST" action="">
                    {% csrf_token %}
                    <table class="table table-bordered mb-0">
                        <thead>                    
                            <tr>
                                <th>Parameter</th>
                                <th>Nilai Minimal</th>
                                <th>Nilai Maksimal</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Nutrisi Air</td>
                                <td>{{ form.min_tds }}</td>
                                <td>{{ form.max_tds }}</td>
                            </tr>
                            <tr>
                                <td>Keasaman Air</td>
                                <td>{{ form.min_ph }}</td>
                                <td>{{ form.max_ph }}</td>
                            </tr>
                            <tr>
                                <td>Suhu Udara</td>
                                <td>{{ form.min_air_temperature }}</td>
                                <td>{{ form.max_air_temperature }}</td>
                            </tr>
                            <tr>
                                <td>Suhu Air</td>
                                <td>{{ form.min_water_temperature }}</td>
                                <td>{{ form.max_water_temperature }}</td>
                            </tr>
                            <tr>
                                <td>Kelembaban Udara</td>
                                <td>{{ form.min_humidity }}</td>
                                <td>{{ form.max_humidity }}</td>
                            </tr>                    
                        </tbody>
                    </table>
                    <br>
                    <button class="btn btn-success" type="submit">
                        <i class="mdi mdi-content-save"> </i>Simpan Perubahan
                    </button>                    
                </form>
            </div> <!-- end card-box -->
        </div>
        


        <div class="col-xl-6">            
            <div class="card-box bx-shadow-lg">
                <h4 class="m-t-0 header-title">Konfigurasi Nilai Ideal Kondisi Tanaman Saat Ini</h4>
                <p>Form untuk menyetel nilai ideal monitoring pada tanaman hidroponik</p>
                <hr>
                
                <table class="table table-bordered mb-0">
                    <thead>                    
                        <tr>
                            <th>Parameter</th>
                            <th>Nilai Minimal</th>
                            <th>Nilai Maksimal</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Nutrisi Air</td>
                            <td><p align="center">{{ sensor_config.min_tds }} PPM</p></td>
                            <td><p align="center">{{ sensor_config.max_tds }} PPM</p></td>
                        </tr>
                        <tr>
                            <td>Keasaman Air</td>
                            <td><p align="center">{{ sensor_config.min_ph }} pH</p></td>
                            <td><p align="center">{{ sensor_config.min_ph }} pH</p></td>
                        </tr>
                        <tr>
                            <td>Suhu Udara</td>
                            <td><p align="center">{{ sensor_config.min_air_temperature }} °C</p></td>
                            <td><p align="center">{{ sensor_config.min_air_temperature }} °C</p></td>
                        </tr>
                        <tr>
                            <td>Suhu Air</td>
                            <td><p align="center">{{ sensor_config.min_water_temperature }} °C</p></td>
                            <td><p align="center">{{ sensor_config.min_water_temperature }} °C</p></td>
                        </tr>
                        <tr>
                            <td>Kelembaban Udara</td>
                            <td><p align="center">{{ sensor_config.min_humidity }} %</p></td>
                            <td><p align="center">{{ sensor_config.min_humidity }} %</p></td>
                        </tr>                    
                    </tbody>
                </table>                
            </div> <!-- end card-box -->
        </div> <!-- end col -->

    <!-- end row -->
    </div>
{% endblock %}

templates/base/dashboard/garden_control.html
{% extends 'include/__main.html' %}
{% load dashboardtags %}
{% load static %}

{% block css %}
    {{ block.super }}
    <!-- Sweet Alert css -->
    <link href="{% static 'libs/sweetalert2/sweetalert2.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'libs/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- Sweet Alert Js  -->
    <script src="{% static 'libs/sweetalert2/sweetalert2.min.js' %}"></script>
    <script src="{% static 'js/jquery.sweet-alert.init.js' %}"></script>
    <script src="{% static 'js/garden_control.js' %}"></script>
{% endblock %}

{% block breadcrumb %}
    <div class="page-title-box">
        <ol class="breadcrumb float-right">
            <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
            <li class="breadcrumb-item active">Kontrol Kebun</li>
        </ol>
        <h4 class="page-title">Kontrol Kebun</h4>
    </div>
{% endblock  %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}

                <div class="alert alert-dismissible bg-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} text-white border-0 fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong></strong> {{ message }}
                </div>

                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-5">
            <p align="center">
                <strong>Pencampur Nutrisi</strong>
                {% if nutrient_value.value > 30 %}
                    {% if sensor_control.status is True %}
                        <a id="button_trigger" href="#" class="disabled btn btn-danger btn-lg border-danger" style="padding-top:60px; width:150px; height:150px;border-radius:50%" id="custom-html-alert">
                            Menyala.
                        </a>
                    {% else %}
                        <button class="btn btn-info btn-lg" style="width:150px; height:150px;border-radius:50%" id="custom-html-alert">
                            Nyalakan!
                        </button>
                    {% endif %}
                {% else %}
                    <a id="button_trigger" href="#" class="disabled btn btn-danger btn-lg border-danger" style="padding-top:60px; width:150px; height:150px;border-radius:50%" id="custom-html-alert">
                        Nutrisi habis
                    </a>
                {% endif %}
            </p>
        </div>
    </div>
    <br>
    <div class="row">
        
        <div class="col-lg-6 ">
            <div class="card-box bx-shadow-lg">
                <h4 class="m-t-0 header-title">Pencampur Nutrisi</h4>
                <p class="text-muted font-13 m-b-20">
                    Status pencampur nutrisi : &nbsp;<button class="btn btn-default btn-sm" id="status_i">inactive</button>
                </p>
                <hr>
                
                <table class="table table-bordered mb-0">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Aktuator</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>Dosing Pump Nutrisi A</td>
                        <td><button class="btn btn-default" align="center" id="pump_nutrient_a">iddle</button></td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Dosing Pump Nutrisi B</td>
                        <td><button class="btn btn-default" align="center" id="pump_nutrient_b">iddle</button></td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>Water Pump</td>
                        <td><button class="btn btn-default" align="center" id="pump_water">iddle</button></td>
                    </tr>
                    </tbody>
                </table>
            </div> <!-- end card-box -->
        </div>


        <div class="col-xl-6">            
            <div class="card-box bx-shadow-lg">
                <h4 class="header-title">Jumlah Ketersediaan Nutrisi Pada Alat</h4>                
                <hr>
                <div class="row">
                    <div class="col-md-6">                
                        <div class="card-box text-center">
                            <input data-plugin="knob" data-width="150" data-height="150" data-linecap=round
                                    data-fgColor="#6b5fb5" value="{{ nutrient_value.value|percentage }}" data-skin="tron" data-angleOffset="180"
                                    data-readOnly=true data-thickness=".1"/>

                            <h6 class="text-muted mt-3">Nutrisi B / %</h6>
                        </div> <!-- end card-box -->
                    </div>
                    <div class="col-md-6">
                        <div class="card-box text-center">
                            <input data-plugin="knob" data-width="150" data-height="150" data-linecap=round
                                    data-fgColor="#6b5fb5" value="{{ nutrient_value.value|percentage }}" data-skin="tron" data-angleOffset="180"
                                    data-readOnly=true data-thickness=".1"/>

                            <h6 class="text-muted mt-3">Nutrisi A / %</h6>
                        </div> <!-- end card-box -->
                    </div>                
                </div>
            </div> <!-- end card-box-->

        </div> <!-- end col -->

    <!-- end row -->
    </div>
{% endblock %}

templates/base/dashboard/password_configuration.html
{% extends 'include/__main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
    {{ block.super }}
    <!-- Sweet Alert css -->
    <link href="{% static 'libs/sweetalert2/sweetalert2.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'libs/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- Sweet Alert Js  -->
    <script src="{% static 'libs/sweetalert2/sweetalert2.min.js' %}"></script>
    <script src="{% static 'js/jquery.sweet-alert.init.js' %}"></script>

{% endblock %}

{% block breadcrumb %}
    <div class="page-title-box">
        <ol class="breadcrumb float-right">
            <li class="breadcrumb-item"><a href="javascript:void(0);">Akun</a></li>
            <li class="breadcrumb-item active">Pengaturan Password Akun</li>
        </ol>
        <h4 class="page-title">Pengaturan Password Akun</h4>
    </div>
{% endblock  %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}

                <div class="alert alert-dismissible bg-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} text-white border-0 fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong></strong> {{ message }}
                </div>

                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        
        <div class="col-lg-6 ">
            <div class="card-box bx-shadow-lg">
                <h4 class="m-t-0 header-title">Pengaturan Akun Pengguna</h4>
                <p>Form untuk mengganti password</p>
                <hr>
                <form action="" method="POST">      
                    {% csrf_token %}                            
                    <div class="form-group">
                        {{ form.old_password|as_crispy_field }}
                    </div>  
                    <div class="form-group">
                        {{ form.new_password1|as_crispy_field }}
                    </div>  
                    <div class="form-group">
                        {{ form.new_password2|as_crispy_field }}
                    </div> 
                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary waves-effect waves-light" type="submit">
                            Simpan Perubahan
                        </button>                        
                    </div>

                </form>
            </div> <!-- end card-box -->
        </div>    

    <!-- end row -->
    </div>
{% endblock %}